[package]
name = "reqreplyv2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zmq = "0.9"

[[bin]]
name = "rep"
path = "src/rep.rs"

[[bin]]
name = "req"
path = "src/req.rs"
